# config/app.yml for rails-settings-cached
defaults: &defaults
  use_sprints: true
  send_emails: true
  retain_activity_days: 60
  retain_notification_days: 30
  default_emails_from: "info@tasktracker.com"
  admin_contact: "admin@tasktracker.com"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
