# config/app.yml for rails-settings-cached
defaults: &defaults
  send_emails: true
  retain_activity_days: 60
  retain_notification_days: 30

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
